<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Prawin-Pc" failures="1" tests="2" name="runner.DemoBlazeTester" time="44.519" errors="0" timestamp="2025-03-08T10:12:07 IST" skipped="0">
  <testcase classname="runner.DemoBlazeTester" name="runScenario" time="22.309"/>
  <system-out/>
  <testcase classname="runner.DemoBlazeTester" name="runScenario" time="22.210">
    <failure message="signup failed expected [Sign up successful.] but found [This user already exist.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: signup failed expected [Sign up successful.] but found [This user already exist.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at stepDefinitions.DemoBlaze.i_should_see_a_successful_registration_message(DemoBlaze.java:67)
at âœ½.I should see a successful registration message(file:///C:/Users/kalai/eclipse-workspace/Phase2Day16Maven/src/test/resources/features/demoblaze.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runner.DemoBlazeTester -->
